//
//  QuotesModel.swift
//  Zeros Cantina
//
//  Created by Anton Zyryanov on 17.07.2025.
//

import Foundation

struct QuotesModel {
    let cards = [
        SwipeableCardModel(text: "Do or do not. There is no try.\n\nYoda"),
        SwipeableCardModel(text: "I find your lack of faith disturbing.\n\nDarth Vader"),
        SwipeableCardModel(text: "The Force will be with you. Always.\n\nObi-Wan Kenobi"),
        SwipeableCardModel(text: "I am your father.\n\nDarth Vader"),
        SwipeableCardModel(text: "Help me, Obi-Wan Kenobi. You're my only hope.\n\nLeia Organa"),
        SwipeableCardModel(text: "In my experience, there is no such thing as luck.\n\nObi-Wan Kenobi"),
        SwipeableCardModel(text: "Fear is the path to the dark side.\n\nYoda"),
        SwipeableCardModel(text: "It's a trap!\n\nAdmiral Ackbar"),
        SwipeableCardModel(text: "The Force is strong with this one.\n\nDarth Vader"),
        SwipeableCardModel(text: "I’ve got a bad feeling about this.\n\nMultiple Characters"),
        SwipeableCardModel(text: "The greatest teacher, failure is.\n\nYoda"),
        SwipeableCardModel(text: "You’re gonna find that many of the truths we cling to depend greatly on our own point of view.\n\nObi-Wan Kenobi"),
        SwipeableCardModel(text: "Your focus determines your reality.\n\nQui-Gon Jinn"),
        SwipeableCardModel(text: "This is the way.\n\nMandalorian Creed"),
        SwipeableCardModel(text: "I am one with the Force. The Force is with me.\n\nThe Mandalorian"),
        SwipeableCardModel(text: "I’ve been waiting for you, Obi-Wan. We meet again, at last.\n\nDarth Vader"),
        SwipeableCardModel(text: "The dark side clouds everything. It’s easiest if you just forget about everything except the fight.\n\nDarth Vader"),
        SwipeableCardModel(text: "The ability to speak does not make you intelligent.\n\nQui-Gon Jinn"),
        SwipeableCardModel(text: "Laugh it up, fuzzball.\n\nHan Solo"),
        SwipeableCardModel(text: "I am a Jedi, like my father before me.\n\nLuke Skywalker"),
        SwipeableCardModel(text: "You are unwise to lower your defenses.\n\nDarth Vader"),
        SwipeableCardModel(text: "The Force will guide us.\n\nRey"),
        SwipeableCardModel(text: "Power! Unlimited power!\n\nEmperor Palpatine"),
        SwipeableCardModel(text: "Size matters not. Look at me. Judge me by my size, do you?\n\nYoda"),
        SwipeableCardModel(text: "The galaxy's a dangerous place.\n\nHan Solo"),
        SwipeableCardModel(text: "I will finish what you started.\n\nLeia Organa"),
        SwipeableCardModel(text: "Much to learn you still have.\n\nYoda"),
        SwipeableCardModel(text: "The force will be with you, always.\n\nObi-Wan Kenobi"),
        SwipeableCardModel(text: "Never tell me the odds.\n\nHan Solo"),
        SwipeableCardModel(text: "The force is strong with this one.\n\nDarth Vader"),
        SwipeableCardModel(text: "How could I be so stupid?\n\nAnakin Skywalker"),
        SwipeableCardModel(text: "I am your father.\n\nDarth Vader"),
        SwipeableCardModel(text: "I’ve got a bad feeling about this.\n\nMultiple Characters"),
        SwipeableCardModel(text: "You don’t know the power of the dark side!\n\nDarth Vader"),
        SwipeableCardModel(text: "The dark side is the path to many abilities some consider to be unnatural.\n\nPalpatine"),
        SwipeableCardModel(text: "I find your lack of faith disturbing.\n\nDarth Vader"),
        SwipeableCardModel(text: "Help me, Obi-Wan Kenobi. You're my only hope.\n\nLeia Organa"),
        SwipeableCardModel(text: "The Force is what gives a Jedi his power.\nQui-Gon Jinn"),
        SwipeableCardModel(text: "I am one with the Force. The Force is with me.\n\nThe Mandalorian"),
        SwipeableCardModel(text: "I will not be the last Jedi.\n\nRey"),
        SwipeableCardModel(text: "The Force surrounds all living things.\n\nYoda"),
        SwipeableCardModel(text: "You underestimate the power of the Dark Side.\n\nDarth Vader"),
        SwipeableCardModel(text: "I’ve got a bad feeling about this.\n\nHan Solo"),
        SwipeableCardModel(text: "The Force is strong with this one.\n\nDarth Vader"),
        SwipeableCardModel(text: "A Jedi's strength flows from the Force.\n\nYoda"),
        SwipeableCardModel(text: "I am your father.\n\nDarth Vader"),
        SwipeableCardModel(text: "Size matters not. Judge me by my size, do you?\n\nYoda"),
        SwipeableCardModel(text: "It's a trap!\n\nAdmiral Ackbar"),
        SwipeableCardModel(text: "Help me, Obi-Wan Kenobi. You're my only hope.\n\nLeia Organa"),
        SwipeableCardModel(text: "The Force will be with you. Always.\n\nObi-Wan Kenobi"),
        SwipeableCardModel(text: "The dark side clouds everything. It’s easiest if you just forget about everything except the fight.\n\nDarth Vader"),
        SwipeableCardModel(text: "The Force is strong with this one.\n\nDarth Vader"),
        SwipeableCardModel(text: "Fear is the path to the dark side.\n\nYoda"),
        SwipeableCardModel(text: "I’ve got a bad feeling about this.\n\nMultiple Characters"),
        SwipeableCardModel(text: "You are unwise to lower your defenses.\n\nDarth Vader"),
        SwipeableCardModel(text: "The force will be with you, always.\n\nObi-Wan Kenobi"),
        SwipeableCardModel(text: "This is the way.\n\nMandalorian Creed"),
        SwipeableCardModel(text: "Never tell me the odds.\n\nHan Solo"),
        SwipeableCardModel(text: "I am a Jedi, like my father before me.\n\nLuke Skywalker"),
        SwipeableCardModel(text: "The galaxy's a dangerous place.\n\nHan Solo"),
        SwipeableCardModel(text: "Might the Force be with us.\n\nMultiple Characters"),
        SwipeableCardModel(text: "The Force is what gives a Jedi his power.\n\nQui-Gon Jinn"),
        SwipeableCardModel(text: "I will finish what you started.\n\nLeia Organa"),
        SwipeableCardModel(text: "Size matters not. Judge me by my size, do you?\n\nYoda"),
        SwipeableCardModel(text: "Help me, Obi-Wan Kenobi. You're my only hope.\n\nLeia Organa"),
        SwipeableCardModel(text: "The Force surrounds all living things.\n\nYoda"),
        SwipeableCardModel(text: "The dark side is the path to many abilities some consider to be unnatural.\n\nPalpatine"),
        SwipeableCardModel(text: "I find your lack of faith disturbing.\n\nDarth Vader"),
        SwipeableCardModel(text: "Help me, Obi-Wan Kenobi. You're my only hope.\n\nLeia Organa"),
        SwipeableCardModel(text: "The Force will be with you. Always.\n\nObi-Wan Kenobi"),
        SwipeableCardModel(text: "This is the way.\n\nMandalorian Creed"),
        SwipeableCardModel(text: "Never tell me the odds.\n\nHan Solo"),
        SwipeableCardModel(text: "The Force is strong with this one.\n\nDarth Vader"),
        SwipeableCardModel(text: "I am a Jedi, like my father before me.\n\nLuke Skywalker"),
        SwipeableCardModel(text: "You underestimate the power of the Dark Side.\n\nDarth Vader")
    ]
}
